# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 10, 17, 6, 639066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=900),
        ),
    ]
