# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_auto_20170223_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 10, 41, 28, 930832, tzinfo=utc)),
        ),
    ]
